### ISSUE TITLE
Add example using multiple model weights files.

### ISSUE THREAD

**Issue by davidslater** [twosixlabs/armory-example#50]

**Comment by jesus-villalba** [comment]
To put you in context, our model consists of multiple blocks and each one has it is own weights file. The way that we have solved that in the configuration file is passing the filename in the model kwargs. For example:
"model": {
    "fit": false,
    "model_kwargs": {
      "xvec_path": "/workspace/models/xvector/model_ep0132.pth",
      "gan_root_dir": "/workspace/models/defense_model_dir"
    },
    "module": "src.models.xvec",
    "name": "get_art_model",
    "weights_file": "",
    "wrapper_kwargs": {}

so we don't use the weights_file field.
I wonder if just submitting the model files and assuming that the are in the working directory would work.

**Comment by davidslater** [comment]
I think that process actually works well. Instead of assuming `/workspace`, though, I would use `paths.runtime_paths().saved_model_dir` and work from there.
```python
>>> from armory import paths
>>> paths.runtime_paths().saved_model_dir
'/Users/davidslater/.armory/saved_models'
>>> from armory import paths
>>> paths.set_mode("docker")
>>> paths.runtime_paths().saved_model_dir
'/armory/saved_models'
>>> paths.set_mode("host")
>>> paths.runtime_paths().saved_model_dir
'/Users/davidslater/.armory/saved_models'
```

So for your kwargs, I would do something like:
```
"model_kwargs": {
"xvec_name": model_ep0132.pth",
...
},
```
```python
xvec_path = os.path.join(paths.runtime_paths().saved_model_dir, model_kwargs["xvec_name"]))
```

Currently, all of the weights will be put directly in the (flat) saved_model_dir. If you *need* hierarchical structure, let me know, and we can probably add a feature that expands a tar file in a specific location and passes in that location.
