### ISSUE TITLE
Module not found for updated scenario

### ISSUE THREAD

**Issue by Aminullah6264** [twosixlabs/armory-example#85]
Hi I am trying to update the scenario but when I execute "armory run" with my edited file, I get the following error. 

Let me know what I am missing?

 
![image](https://user-images.githubusercontent.com/15268491/122301351-6d1dbd00-ceb5-11eb-991e-faf1536d8f55.png)

I run the armory interactive which show all file exists. 

![image](https://user-images.githubusercontent.com/15268491/122301514-a1917900-ceb5-11eb-9293-7775729f886c.png)

![image](https://user-images.githubusercontent.com/15268491/122301723-ef0de600-ceb5-11eb-8622-30db7de122c6.png)

**Comment by ng390** [comment]
Do you get the same error when running the command as ```python -m armory run cifar10_baseline_edited.json```?

**Comment by Aminullah6264** [comment]
Yes, same error. 

![image](https://user-images.githubusercontent.com/15268491/122304156-9e988780-ceb9-11eb-94ab-43063887f529.png)

**Comment by Aminullah6264** [comment]
I solved this by editing file in docker container folder /opt/conda/lib/python3.7/site-packages/armory/scenarios
